LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/AM.dat' INTO TABLE PUBACC_AM FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/CO.dat' INTO TABLE PUBACC_CO FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/EN.dat' INTO TABLE PUBACC_EN FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/HD.dat' INTO TABLE PUBACC_HD FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/HS.dat' INTO TABLE PUBACC_HS FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/LA.dat' INTO TABLE PUBACC_LA FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/SC.dat' INTO TABLE PUBACC_SC FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE '/home/n00tz/ULSDATA/amat/SF.dat' INTO TABLE PUBACC_SF FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
