LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/AM.dat' INTO TABLE PUBACC_AM FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/CO.dat' INTO TABLE PUBACC_CO FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/EN.dat' INTO TABLE PUBACC_EN FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/HD.dat' INTO TABLE PUBACC_HD FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/HS.dat' INTO TABLE PUBACC_HS FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/LA.dat' INTO TABLE PUBACC_LA FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/SC.dat' INTO TABLE PUBACC_SC FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE '{{ DIR }}/FCCULS-mysql/amat/SF.dat' INTO TABLE PUBACC_SF FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
