LOAD DATA INFILE 'CO.dat' INTO TABLE TOWER_PUBACC_CO FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'EN.dat' INTO TABLE TOWER_PUBACC_EN FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'HS.dat' INTO TABLE TOWER_PUBACC_HS FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'RA.dat' INTO TABLE TOWER_PUBACC_RA FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'SC.dat' INTO TABLE TOWER_PUBACC_SC FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
LOAD DATA INFILE 'RE.dat' INTO TABLE TOWER_PUBACC_RE FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';
